// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EntradaMensajeClient is the client API for EntradaMensaje service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EntradaMensajeClient interface {
	Intercambio(ctx context.Context, in *Mensaje, opts ...grpc.CallOption) (*Mensaje, error)
}

type entradaMensajeClient struct {
	cc grpc.ClientConnInterface
}

func NewEntradaMensajeClient(cc grpc.ClientConnInterface) EntradaMensajeClient {
	return &entradaMensajeClient{cc}
}

func (c *entradaMensajeClient) Intercambio(ctx context.Context, in *Mensaje, opts ...grpc.CallOption) (*Mensaje, error) {
	out := new(Mensaje)
	err := c.cc.Invoke(ctx, "/grpc.EntradaMensaje/Intercambio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntradaMensajeServer is the server API for EntradaMensaje service.
// All implementations must embed UnimplementedEntradaMensajeServer
// for forward compatibility
type EntradaMensajeServer interface {
	Intercambio(context.Context, *Mensaje) (*Mensaje, error)
	mustEmbedUnimplementedEntradaMensajeServer()
}

// UnimplementedEntradaMensajeServer must be embedded to have forward compatible implementations.
type UnimplementedEntradaMensajeServer struct {
}

func (UnimplementedEntradaMensajeServer) Intercambio(context.Context, *Mensaje) (*Mensaje, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Intercambio not implemented")
}
func (UnimplementedEntradaMensajeServer) mustEmbedUnimplementedEntradaMensajeServer() {}

// UnsafeEntradaMensajeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntradaMensajeServer will
// result in compilation errors.
type UnsafeEntradaMensajeServer interface {
	mustEmbedUnimplementedEntradaMensajeServer()
}

func RegisterEntradaMensajeServer(s grpc.ServiceRegistrar, srv EntradaMensajeServer) {
	s.RegisterService(&EntradaMensaje_ServiceDesc, srv)
}

func _EntradaMensaje_Intercambio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mensaje)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntradaMensajeServer).Intercambio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.EntradaMensaje/Intercambio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntradaMensajeServer).Intercambio(ctx, req.(*Mensaje))
	}
	return interceptor(ctx, in, info, handler)
}

// EntradaMensaje_ServiceDesc is the grpc.ServiceDesc for EntradaMensaje service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntradaMensaje_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.EntradaMensaje",
	HandlerType: (*EntradaMensajeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Intercambio",
			Handler:    _EntradaMensaje_Intercambio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mensaje.proto",
}
